In [165]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
df = pd.read_csv("./FAO.csv")

In [45]:
df.head()

,Country (Name),ASFIS species (Name),FAO major fishing area (Name),Environment (Name),Unit (Name),Unit,[1984],S,[1985],S.1,...,[2020],S.36,[2021],S.37,[2022],S.38,[2023],S.39,[2024],S.40
0,Madagascar,Brine shrimp,"Indian Ocean, Western",Marine,Value (USD 1000),USD (1000),0.00,NaN,0.00,NaN,...,0.00,...,0.00,...,0.00,...,0.00,...,0.00,...
1,Madagascar,Common carp,Africa - Inland waters,Freshwater,Value (USD 1000),USD (1000),488.53,NaN,317.52,NaN,...,42.24,I,113.30,NaN,2049.63,NaN,2903.56,NaN,15574.23,NaN
2,Madagascar,Eucheuma seaweeds NEI,"Indian Ocean, Western",Marine,Value (USD 1000),USD (1000),0.00,...,0.00,...,...,1494.07,NaN,2130.72,NaN,2702.93,NaN,4391.13,NaN,4426.84,NaN
3,Madagascar,Freshwater fishes NEI,Africa - Inland waters,Freshwater,Value (USD 1000),USD (1000),0.00,...,0.00,...,...,21.12,I,20.89,I,19.53,I,20.32,I,19.89,I
4,Madagascar,Giant tiger prawn,"Indian Ocean, Western",Brackishwater,Value (USD 1000),USD (1000),0.00,...,0.00,...,...,52204.12,NaN,33517.68,NaN,65026.96,NaN,52137.18,NaN,54211.12,NaN

In [46]:
df.drop(columns=["Country (Name)","FAO major fishing area (Name)","Environment (Name)","Unit (Name)","Unit"],inplace=True)

In [49]:
df.head()

,ASFIS species (Name),[1984],S,[1985],S.1,[1986],S.2,[1987],S.3,[1988],...,[2020],S.36,[2021],S.37,[2022],S.38,[2023],S.39,[2024],S.40
0,Brine shrimp,0.00,NaN,0.00,NaN,0.00,NaN,0.00,NaN,0.00,...,0.00,...,0.00,...,0.00,...,0.00,...,0.00,...
1,Common carp,488.53,NaN,317.52,NaN,259.43,NaN,218.84,NaN,200.56,...,42.24,I,113.30,NaN,2049.63,NaN,2903.56,NaN,15574.23,NaN
2,Eucheuma seaweeds NEI,0.00,...,0.00,...,0.00,...,0.00,...,0.00,...,1494.07,NaN,2130.72,NaN,2702.93,NaN,4391.13,NaN,4426.84,NaN
3,Freshwater fishes NEI,0.00,...,0.00,...,0.00,...,0.00,...,0.00,...,21.12,I,20.89,I,19.53,I,20.32,I,19.89,I
4,Giant tiger prawn,0.00,...,0.00,...,0.00,...,0.00,...,0.00,...,52204.12,NaN,33517.68,NaN,65026.96,NaN,52137.18,NaN,54211.12,NaN

In [51]:
for c in df.columns:
    if(c[0].lower() == "s"):
        df.drop(columns=[c],inplace=True)

In [111]:
df= df[-df["ASFIS species (Name)"].isna()]

In [67]:
n = len(df.columns)-1

In [119]:
df["ASFIS species (Name)"].nunique()

13

In [69]:
sns.lineplot(data=df,x=range(n),y=)

41

In [115]:
df_long = df.melt(
    id_vars=["ASFIS species (Name)"], 
    var_name="Year", 
    value_name="Production"
)

In [117]:
df_long

      ASFIS species (Name)    Year  Production
0             Brine shrimp  [1984]        0.00
1              Common carp  [1984]      488.53
2    Eucheuma seaweeds NEI  [1984]        0.00
3    Freshwater fishes NEI  [1984]        0.00
4        Giant tiger prawn  [1984]        0.00
..                     ...     ...         ...
528          Rainbow trout  [2024]        0.00
529               Sandfish  [2024]     2906.14
530      Sea cucumbers NEI  [2024]        0.00
531          Sturgeons NEI  [2024]        1.16
532           Tilapias NEI  [2024]        0.00

[533 rows x 3 columns]

In [145]:
df_test = df_long.pivot(index="Year",columns=["ASFIS species (Name)"],values="Production")

In [149]:
df_test.reset_index(inplace=True)

In [155]:
df_test.columns

Index(['Year', 'Brine shrimp', 'Common carp', 'Eucheuma seaweeds NEI',
       'Freshwater fishes NEI', 'Giant tiger prawn', 'Indo-Pacific swamp crab',
       'Indonesian shortfin eel', 'Nile tilapia', 'Rainbow trout', 'Sandfish',
       'Sea cucumbers NEI', 'Sturgeons NEI', 'Tilapias NEI'],
      dtype='object', name='ASFIS species (Name)')

In [161]:
df_test = df_test[df_test.columns[1:]]

In [163]:
plt.plot()

ASFIS species (Name),Brine shrimp,Common carp,Eucheuma seaweeds NEI,Freshwater fishes NEI,Giant tiger prawn,Indo-Pacific swamp crab,Indonesian shortfin eel,Nile tilapia,Rainbow trout,Sandfish,Sea cucumbers NEI,Sturgeons NEI,Tilapias NEI
0,0.0,488.53,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,9.81
1,0.0,317.52,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,89.51
2,0.0,259.43,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,53.68
3,0.0,218.84,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,45.69
4,0.0,200.56,0.00,0.00,0.00,0.0,0.00,0.00,3.86,0.00,0.0,0.00,39.04
5,0.0,189.70,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,34.94
6,0.0,276.00,0.00,0.00,90.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,36.00
7,0.0,218.80,0.00,0.00,415.72,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
8,0.0,2548.68,410.00,0.00,160.80,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
9,0.0,2398.40,0.00,0.00,4131.70,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
10,0.0,4474.85,0.00,0.00,2162.40,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
11,0.0,2986.38,0.00,0.00,7675.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
12,0.0,3272.75,0.00,0.00,13337.50,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
13,0.0,7216.11,0.00,0.00,13623.50,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
14,0.0,2960.19,0.00,0.00,13706.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
15,0.0,3743.25,0.00,0.00,17430.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
16,0.0,3720.00,94.50,0.00,24000.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
17,0.0,3572.00,94.50,0.00,26995.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
18,0.0,3600.00,94.50,0.00,36565.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
19,0.0,4900.00,108.00,0.00,35035.00,0.0,0.00,4.80,0.00,0.00,0.0,0.00,0.00
20,0.0,5100.00,108.00,0.00,31215.00,0.0,0.00,16.50,0.00,0.00,0.0,0.00,0.00
21,0.0,4571.25,121.50,0.00,33630.00,0.0,0.00,34.50,0.00,0.00,0.0,0.00,0.00
22,0.0,4911.50,715.50,0.00,42315.00,0.0,0.00,35.72,0.00,0.00,4.0,0.00,0.00
23,0.0,5239.96,492.75,0.00,42285.00,25.0,0.00,60.95,0.00,0.00,4.0,0.00,0.00
24,0.0,5754.17,492.75,0.00,40000.00,25.0,0.00,61.65,0.00,0.00,4.0,0.00,0.00
25,0.0,4998.00,486.00,0.00,16300.00,25.0,200.00,53.55,0.00,0.00,4.0,0.00,0.00
26,0.0,4689.11,540.00,0.00,20000.00,25.0,300.00,83.73,0.00,0.00,4.0,0.00,0.00
27,0.0,11579.58,142.62,0.00,40034.71,25.0,207.40,172.83,35.55,0.00,4.0,0.00,0.00
28,0.0,12902.25,108.43,0.00,29325.96,25.0,255.13,182.24,0.00,0.00,4.0,0.00,0.00
29,0.0,9424.92,275.38,0.00,36444.55,25.0,63.44,4109.81,806.56,0.00,4.0,0.00,0.00
30,0.0,8613.51,1443.18,0.00,29138.92,25.0,57.98,4816.11,0.00,0.00,4.0,0.00,0.00
31,0.0,7090.49,2620.92,0.00,17625.65,25.0,96.45,4158.84,0.00,255.67,0.0,0.00,0.00
32,0.0,7933.16,2742.45,0.00,55377.09,25.0,0.00,5036.93,0.00,339.99,0.0,0.00,0.00
33,0.0,11264.04,2793.10,16.05,63150.21,25.0,0.00,6033.16,0.00,951.19,0.0,0.00,0.00
34,0.0,166.38,800.21,22.49,56523.55,50.0,43.37,10671.26,0.00,449.81,0.0,100.00,0.00
35,0.0,54.17,1224.96,22.11,40841.99,50.0,1.55,3761.35,0.00,414.56,0.0,700.00,0.00
36,0.0,42.24,1494.07,21.12,52204.12,50.0,0.00,540.56,0.00,396.01,0.0,1125.00,0.00
37,0.0,113.30,2130.72,20.89,33517.68,50.0,0.00,5424.91,0.00,979.26,0.0,3960.00,0.00
38,0.0,2049.63,2702.93,19.53,65026.96,50.0,0.00,6070.77,0.00,11381.58,0.0,3150.00,0.00
39,0.0,2903.56,4391.13,20.32,52137.18,125.0,0.00,11614.31,0.00,2988.73,0.0,4140.00,0.00
40,0.0,15574.23,4426.84,19.89,54211.12,124.3,0.00,32705.85,0.00,2906.14,0.0,1.16,0.00